api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('', views.index, name='index')
]

apps/urls.py
from django.urls import path

from . import views

app_name = 'apps'
urlpatterns = [
    path('', views.index, name='index'),
    path("<str:name>", views.app, name="app")
]

webui/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('mgmt.urls')),
    path('apps/', include('apps.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load bootstrap4 %}
{% load static %}


<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Cluster in the Cloud</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>

<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-2 mr-0" href="{% url 'index' %}">Cluster in the Cloud</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Sign out</a>
            {% else %}
                <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Sign in</a>
            {% endif %}
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-2 d-md-block bg-light sidebar collapse">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        {% url 'index' as url %}
                        <a class="nav-link {% if request.path == url %}active{% endif %}" {% if request.path == url %}aria-current="page"{% endif %} href="{{ url }}">
                            <span data-feather="home"></span>
                            Dashboard
                        </a>
                    </li>
                    <li class="nav-item">
                        {% url 'users' as url %}
                        <a class="nav-link {% if request.path == url %}active{% endif %}" {% if request.path == url %}aria-current="page"{% endif %} href="{{ url }}">
                            <span data-feather="users"></span>
                            Users
                        </a>
                    </li>
                    <li class="nav-item">
                        {% url 'apps:index' as url %}
                        <a class="nav-link {% if request.path == url %}active{% endif %}" {% if request.path == url %}aria-current="page"{% endif %} href="{{ url }}">
                            <span data-feather="list"></span>
                            Apps
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            {% bootstrap_messages %}
            {% block content %}{% endblock %}
        </main>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
{% bootstrap_javascript jquery='full' %}
<script>
    feather.replace()
</script>
</body>
</html>

templates/base_login.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Cluster in the Cloud</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">
</head>

<body class="text-center">

{% block content %}{% endblock %}

</body>
</html>